version: "3"
services:
  threads1:
    image: textile/go-threads:latest
    restart: always
    volumes:
      - "./repo/threads1:/data/threads"
    environment:
      - THRDS_HOSTADDR=/ip4/0.0.0.0/tcp/4006
      - THRDS_APIADDR=/ip4/0.0.0.0/tcp/6006
      - THRDS_APIPROXYADDR=/ip4/0.0.0.0/tcp/6007
      - THRDS_DEBUG=true
    ports:
      - "4006:4006"
      - "127.0.0.1:6006:6006"
      - "127.0.0.1:6007:6007"
  threads2:
    image: textile/go-threads:latest
    restart: always
    volumes:
      - "./repo/threads2:/data/threads"
    environment:
      - THRDS_HOSTADDR=/ip4/0.0.0.0/tcp/4006
      - THRDS_APIADDR=/ip4/0.0.0.0/tcp/6006
      - THRDS_APIPROXYADDR=/ip4/0.0.0.0/tcp/6007
      - THRDS_DEBUG=true
    ports:
      - "4206:4006"
      - "127.0.0.1:6206:6006"
      - "127.0.0.1:6207:6007"
